/***************************************************************************
 # Copyright (c) 2015-21, NVIDIA CORPORATION. All rights reserved.
 #
 # NVIDIA CORPORATION and its licensors retain all intellectual property
 # and proprietary rights in and to this software, related documentation
 # and any modifications thereto.  Any use, reproduction, disclosure or
 # distribution of this software and related documentation without an express
 # license agreement from NVIDIA CORPORATION is strictly prohibited.
 **************************************************************************/

/** Dummy compute program for reflection of the structured buffer types.

    Falcor requires reflection data to be able to create a structured buffer,
    but the programs are not yet ready to be used when we create the buffers.
    Therefore we create this dummy program to make it easier.
 */

import PathReservoir;
import PathTracer;

StructuredBuffer<PathReservoir> pathReservoirs;
StructuredBuffer<ReconnectionData> reconnectionDataBuffer;
ParameterBlock<PathTracer> pathTracer;
StructuredBuffer<NeighborValidMask> neighborValidMask;
StructuredBuffer<ReSTIRPTVertexFull> scratchVertices;
StructuredBuffer<ReSTIRPTVertexNEE> neeVertices;
StructuredBuffer<ReSTIRPTVertex> pathVertices;
StructuredBuffer<SubpathPrecomputedInfo> subpathPrecomputedInfo;
StructuredBuffer<PrefixGBuffer> prefixGBuffer;
StructuredBuffer<uint> temporalNeighborPixels;
StructuredBuffer<PrefixReservoir> prefixReservoirs;
StructuredBuffer<uint> rcBufferOffsets;
StructuredBuffer<PrefixInfo> prefixThroughputs;
StructuredBuffer<PrefixSearchKey> prefixSearchKeys;
StructuredBuffer<PackedBoundingBox> searchPointBoundingBoxBuffer;
StructuredBuffer<float> prefixL2LengthBuffer;

void main() {}
